- name: Provision kone-db database
  vars:
    simple_postgres_admin_host: "{{ oodikone_postgres_admin_host }}"
    simple_postgres_admin_port: "{{ oodikone_postgres_admin_port }}"
    simple_postgres_admin_user: "{{ oodikone_postgres_admin_user }}"
    simple_postgres_admin_password: "{{ oodikone_postgres_admin_password }}"
    simple_postgres_database_read_users: "{{ oodikone_postgres_read_users }}"
    simple_postgres_database_admin_users: "{{ oodikone_postgres_admin_users }}"

    simple_postgres_database: "{{ oodikone_postgres_kone_db_database }}"
  import_role:
    name: simple_postgres_database
  tags:
    - oodikone_postgres_database 
    - oodikone_kone_db_database

- name: Provision sis-db database
  vars:
    simple_postgres_admin_host: "{{ oodikone_postgres_admin_host }}"
    simple_postgres_admin_port: "{{ oodikone_postgres_admin_port }}"
    simple_postgres_admin_user: "{{ oodikone_postgres_admin_user }}"
    simple_postgres_admin_password: "{{ oodikone_postgres_admin_password }}"
    simple_postgres_database_read_users: "{{ oodikone_postgres_read_users }}"
    simple_postgres_database_admin_users: "{{ oodikone_postgres_admin_users }}"

    simple_postgres_database: "{{ oodikone_postgres_sis_db_database }}"
  import_role:
    name: simple_postgres_database
  tags:
    - oodikone_postgres_database 
    - oodikone_kone_db_database

- name: Provision user-db database
  vars:
    simple_postgres_admin_host: "{{ oodikone_postgres_admin_host }}"
    simple_postgres_admin_port: "{{ oodikone_postgres_admin_port }}"
    simple_postgres_admin_user: "{{ oodikone_postgres_admin_user }}"
    simple_postgres_admin_password: "{{ oodikone_postgres_admin_password }}"
    simple_postgres_database_read_users: "{{ oodikone_postgres_read_users }}"
    simple_postgres_database_admin_users: "{{ oodikone_postgres_admin_users }}"

    simple_postgres_database: "{{ oodikone_postgres_user_db_database }}"
  import_role:
    name: simple_postgres_database
  tags:
    - oodikone_postgres_database 
    - oodikone_kone_db_database

