# Note that simple_postgres_admin_* vars are defined in this roles vars/main.yml

- name: Provision kone-db database
  vars:
    simple_postgres_database: "{{ oodikone_postgres_kone_db_database }}"
  import_role:
    name: simple_postgres_database
  tags:
    - oodikone_postgres_database 
    - oodikone_kone_db_database

- name: Provision sis-db database
  vars:
    simple_postgres_database: "{{ oodikone_postgres_sis_db_database }}"
  import_role:
    name: simple_postgres_database
  tags:
    - oodikone_postgres_database 
    - oodikone_kone_db_database

- name: Provision user-db database
  vars:
    simple_postgres_database: "{{ oodikone_postgres_user_db_database }}"
  import_role:
    name: simple_postgres_database
  tags:
    - oodikone_postgres_database 
    - oodikone_kone_db_database

