- name: System group
  group:
    gid: "{{ nats_gid }}"
    name: nats
    state: present
    system: true
  tags:
    - nats_user

- name: System user
  user:
    uid: "{{ nats_uid }}"
    name: nats
    group: nats
    state: present
    system: true
    create_home: false
  tags:
    - nats_user

- name: Config directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: root
    group: nats
  with_items:
    - /opt/nats

- name: Create NATS configuration file
  template:
    src: "nats.cfg.j2"
    dest: /opt/nats/nats.cfg
    owner: root
    group: nats
    mode: 0640
  diff: "{{ diff_secrets | default(false) }}"
  notify: restart nats
  tags: nats_cfg

- name: Data directory
  file:
    path: "{{ aws_nats_data_path }}/datastore"
    state: directory
    owner: root
    group: "{{ nats_gid }}"
    mode: 0775

- name: Pull NATS Docker image
  docker_image:
    name: "{{ nats_docker_image }}"
    state: present
    source: pull
    force_source: yes
  tags: nats_docker_image

- name: Deploy NATS Docker container
  vars:
    cmd_args:
      # https://nats-io.gitbook.io/legacy-nats-docs/nats-streaming-server-aka-stan/stan-nats-streaming-server/configuring/command-line-arguments
      # args that do not work from nats.cfg
      stan_config: /opt/nats/nats.cfg
      http_port: "{{ nats_http_port }}"
      port: "{{ nats_client_port }}"
      store: file
      dir: /datastore
  docker_container:
    name: nats
    image: "{{ nats_docker_image }}"
    state: started
    restart_policy: unless-stopped
    network_mode: host
    user: "{{ nats_uid }}:{{ nats_gid }}"
    command: "{% for key, value in cmd_args | dictsort %}--{{ key }} {{ value }} {% endfor %}"
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - "{{ aws_nats_data_path }}/datastore:/datastore:rw"
      - "/opt/nats:/opt/nats:ro"
    cap_drop:
      - net_raw
    log_driver: "{{ docker_log_driver }}"
    log_options: "{{ docker_log_opts | combine({ 'tag': 'nats' }) }}"
  register: nats_docker_container
  tags: nats_docker_container
