sis_importer_postgres_username: "{{ sis_importer_postgres_prefix }}"
sis_importer_postgres_password: "{{ postgres_passwords[sis_importer_postgres_username] }}"

sis_importer_postgres_importer_db_database:
  name: "{{ sis_importer_postgres_prefix }}_importer-db"
  user: "{{ sis_importer_postgres_username }}"
  password: "{{ sis_importer_postgres_password }}"
