- name: System group
  group:
    gid: "{{ oodikone_gid }}"
    name: oodikone
    state: present
    system: true

- name: System user
  user:
    uid: "{{ oodikone_uid }}"
    name: oodikone
    group: oodikone
    state: present
    system: true
    create_home: false

- name: Config directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: root
    group: oodikone
  with_items:
    - /opt/oodikone-backend
    - /opt/oodikone-backend/config

- name: Generate env secrets
  copy:
    content: |
      IMPORTER_DB_API_TOKEN={{ oodikone_importer_db_api_token }}
      PATE_TOKEN={{ oodikone_pate_token }}
      CRYPT_KEY={{ oodikone_crypt_key }}
      SECRET_TOKEN={{ oodikone_secret_token }}
      SIS_GRAPHQL_APPLICATION_KEY={{ oodikone_sis_application_account_key }}
      DB_URL_KONE=postgres://{{ oodikone_postgres_kone_db_database.user }}:{{ oodikone_postgres_kone_db_database.password }}@{{ oodikone_postgres_host }}:{{ oodikone_postgres_port }}/{{ oodikone_postgres_kone_db_database.name }}
      DB_URL_USER=postgres://{{ oodikone_postgres_user_db_database.user }}:{{ oodikone_postgres_user_db_database.password }}@{{ oodikone_postgres_host }}:{{ oodikone_postgres_port }}/{{ oodikone_postgres_user_db_database.name }}
      SIS_DB_URL=postgres://{{ oodikone_postgres_sis_db_database.user }}:{{ oodikone_postgres_sis_db_database.password }}@{{ oodikone_postgres_host }}:{{ oodikone_postgres_port }}/{{ oodikone_postgres_sis_db_database.name }}
    dest: /opt/oodikone-backend/secrets.env
    owner: root
    group: oodikone
    mode: 0640
  diff: "{{ diff_secrets | default(false) }}"
  tags: oodikone_backend_secret_envs

## backend
- name: Pull backend Docker image
  docker_image:
    name: "{{ oodikone_backend_docker_image }}"
    state: present
    source: pull
    force_source: yes
  tags: oodikone_backend_docker_image

- name: Generate backend organisationConfig
  copy:
    content: |
      {{ oodikone_backend_organisation_config | to_nice_json }}
    dest: /opt/oodikone-backend/config/organizationConfig.json
    owner: root
    group: oodikone
    mode: 0644
  tags: oodikone_backend_configs_json


- name: Deploy backend Docker container
  docker_container:
    name: oodikone.backend
    image: "{{ oodikone_backend_docker_image }}"
    state: started
    restart_policy: unless-stopped
    network_mode: host
    user: "{{ oodikone_uid }}:{{ oodikone_gid }}"
    env:
      FRONT_URL: "http://localhost:{{ oodikone_frontend_http_port }}"
      REDIS: localhost
      SIS_UPDATER_URL: "{{ oodikone_sis_updater_scheduler_url }}"
      IMPORTER_DB_API_URL: "{{ oodikone_sis_importer_db_api_url }}"
      JAMI_URL: 'http://jami:3003/' # TODO
      SERVICE_PROVIDER: 'Fd'
      LOGOUT_URL: "{{ oodikone_nginx_env_configs.logoutUrl }}"
      NODE_ENV: development # changing this to production breaks login
      REACT_APP_STAGING: 'false'
      SENTRY_ENVIRONMENT: ''
      SENTRY_RELEASE: ''
      SIS_HOST: "{{ oodikone_sis_host }}"
      SIS_GRAPHQL_APPLICATION_ACCOUNT: "{{ oodikone_sis_application_account }}"
      ROOT_ORG_ID: "{{ oodikone_root_org_id }}"
    env_file: /opt/oodikone-backend/secrets.env
    read_only: true
    volumes:
      - /opt/oodikone-backend/config:/opt/app-root/src/dist/src/environment:ro
    tmpfs:
      - /tmp
    cap_drop:
      - net_raw
    log_driver: "{{ docker_log_driver }}"
    log_options: "{{ docker_log_opts | combine({ 'tag': 'oodikone.backend' }) }}"
  register: oodikone_backend_docker_container
  tags: oodikone_backend_docker_container

- name: Wait for oodikone.backend startup
  uri:
    url: "http://127.0.0.1:{{ oodikone_backend_http_port }}/"
    method: GET
    status_code: [200,403] # backend expects authenticated requests
  register: result
  when: not ansible_check_mode
  until: result.status in [200,403]
  retries: 60
  delay: 1
  tags: oodikone_backend_wait
