- name: System group
  group:
    gid: "{{ oodikone_gid }}"
    name: oodikone
    state: present
    system: true

- name: System user
  user:
    uid: "{{ oodikone_uid }}"
    name: oodikone
    group: oodikone
    state: present
    system: true
    create_home: false

- name: Config directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: root
    group: oodikone
  with_items:
    - /opt/oodikone-sis-updater-worker

- name: Generate env secrets
  copy:
    content: |
      SIS_IMPORTER_PASSWORD={{ sis_importer_postgres_importer_db_database.password }}
      SECRET_TOKEN={{ oodikone_secret_token }}
      DB_URL=postgres://{{ oodikone_postgres_sis_db_database.user }}:{{ oodikone_postgres_sis_db_database.password }}@{{ oodikone_postgres_host }}:{{ oodikone_postgres_port }}/{{ oodikone_postgres_sis_db_database.name }}
    dest: /opt/oodikone-sis-updater-worker/secrets.env
    owner: root
    group: oodikone
    mode: 0640
  diff: "{{ diff_secrets | default(false) }}"
  tags: oodikone_sis_updater_worker_secret_envs

- name: Pull oodikone.sis-updater-worker Docker image
  docker_image:
    name: "{{ oodikone_sis_updater_worker_docker_image }}"
    state: present
    source: pull
    force_source: yes
  tags: oodikone_sis_updater_worker_docker_image

- name: Deploy oodikone.sis-updater-worker Docker container
  docker_container:
    name: oodikone.sis-updater-worker
    image: "{{ oodikone_sis_updater_worker_docker_image }}"
    labels:
      fi.funidata.oodikone.application: sis-updater-worker
      fi.funidata.oodikone.deploy: "{{ oodikone_version }}"
      fi.funidata.oodikone.site: "{{ oodikone_site }}"
    state: started
    restart_policy: unless-stopped
    network_mode: host
    user: "{{ oodikone_uid }}:{{ oodikone_gid }}"
    env:
      REDIS_URI: "{{ oodikone_valkey_uri }}"
      REDIS_HOST: "{{ oodikone_valkey_host }}"
      REDIS_PORT: "{{ oodikone_valkey_port }}"
      SIS_IMPORTER_DATABASE: "{{ sis_importer_postgres_importer_db_database.name }}"
      SIS_IMPORTER_HOST: "{{ oodikone_postgres_host }}"
      SIS_IMPORTER_USER: "{{ sis_importer_postgres_importer_db_database.user }}" # TODO should probably be a read only user
      HOSTNAME: "{{ oodikone_site }}-worker" # defines NATS client_id
      ROOT_ORG_ID: "{{ oodikone_root_org_id }}"
      SERVICE_PROVIDER: fd
      NODE_ENV: "{{ oodikone_node_env }}"
      SENTRY_ENVIRONMENT: ""
      SENTRY_RELEASE: ""
      SENTRY_DSN: ""
      NODE_OPTIONS: "--max-old-space-size={{ oodikone_sis_updater_worker_max_old_space_size }}"
    env_file: /opt/oodikone-sis-updater-worker/secrets.env
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - net_raw
    log_driver: "{{ docker_log_driver }}"
    log_options: "{{ docker_log_opts | combine({ 'tag': 'oodikone.sis-updater-worker' }) }}"
  register: oodikone_sis_updater_worker_docker_container
  tags: oodikone_sis_updater_worker_docker_container
