- name: "Setting up database {{ simple_postgres_database.name }}"
  debug:
    msg: "{{ simple_postgres_database.name }}"

- name: Install ansible dependencies
  import_role:
    name: funidata.infra.ansible_postgresql
  tags: ansible_postgresql

- name: Provision database user
  postgresql_user:
    login_host: "{{ simple_postgres_admin_host }}"
    login_port: "{{ simple_postgres_admin_port }}"
    login_user: "{{ simple_postgres_admin_user }}"
    login_password: "{{ simple_postgres_admin_password }}"

    name: "{{ simple_postgres_database.user }}"
    password: "{{ simple_postgres_database.password }}"
    encrypted: true
    role_attr_flags: LOGIN
    no_password_changes: "{{ not (simple_postgres_database_password_changes | bool) }}"
  tags: simple_postgres_database_users

- name: Grant role membership to postgres
  postgresql_membership:
    login_host: "{{ simple_postgres_admin_host }}"
    login_port: "{{ simple_postgres_admin_port }}"
    login_user: "{{ simple_postgres_admin_user }}"
    login_password: "{{ simple_postgres_admin_password }}"
    login_db: postgres

    users:
      - "{{ simple_postgres_admin_user }}"
    groups:
      - "{{ simple_postgres_database.user }}"
  tags: simple_postgres_database_users

- name: Provision database
  postgresql_db:
    login_host: "{{ simple_postgres_admin_host }}"
    login_port: "{{ simple_postgres_admin_port }}"
    login_user: "{{ simple_postgres_admin_user }}"
    login_password: "{{ simple_postgres_admin_password }}"

    name: "{{ simple_postgres_database.name }}"
    owner: "{{ simple_postgres_database.user }}"
    template: template0
    encoding: "{{ simple_postgres_database_encoding }}"
    lc_collate: "{{ simple_postgres_database_locale }}"
    lc_ctype: "{{ simple_postgres_database_locale }}"
  tags: simple_postgres_database

# https://aws.amazon.com/premiumsupport/knowledge-center/rds-postgresql-revoke-public-schema/
- name: Alter public schema owner
  postgresql_owner:
    login_host: "{{ simple_postgres_admin_host }}"
    login_port: "{{ simple_postgres_admin_port }}"
    login_user: "{{ simple_postgres_admin_user }}"
    login_password: "{{ simple_postgres_admin_password }}"

    # ALTER SCHEMA public OWNER TO ...
    db: "{{ simple_postgres_database.name }}"
    obj_type: schema
    obj_name: public
    new_owner: "{{ simple_postgres_database.user }}"
  tags: simple_postgres_database_public

- name: Revoke database privileges from public
  postgresql_privs:
    login_host: "{{ simple_postgres_admin_host }}"
    login_port: "{{ simple_postgres_admin_port }}"
    login_user: "{{ simple_postgres_admin_user }}"
    login_password: "{{ simple_postgres_admin_password }}"

    state: absent
    database: "{{ simple_postgres_database.name }}"
    type: database
    privs: CONNECT,TEMP
    role: PUBLIC
  tags: simple_postgres_database_public

- name: Revoke schema privileges from public
  postgresql_privs:
    login_host: "{{ simple_postgres_admin_host }}"
    login_port: "{{ simple_postgres_admin_port }}"
    login_user: "{{ simple_postgres_admin_user }}"
    login_password: "{{ simple_postgres_admin_password }}"

    # REVOKE CREATE, USAGE PRIVILEGES ON SCHEMA public FROM public
    state: absent
    database: "{{ simple_postgres_database.name }}"
    type: schema
    privs: CREATE,USAGE
    objs: public
    role: PUBLIC
  tags: simple_postgres_database_public

- name: Load database extensions
  postgresql_ext:
    login_host: "{{ simple_postgres_admin_host }}"
    login_port: "{{ simple_postgres_admin_port }}"
    login_user: "{{ simple_postgres_admin_user }}"
    login_password: "{{ simple_postgres_admin_password }}"

    db: "{{ simple_postgres_database.name }}"
    name: "{{ db_extension.name }}"
    state: present
    version: "{{ db_extension.version | default(omit) }}"
  loop: "{{ simple_postgres_database_extensions }}"
  loop_control:
    loop_var: db_extension
  tags: simple_postgres_database_extensions

- name: Configure database settings
  funidata.infra.postgresql_database_setting:
    login_host: "{{ simple_postgres_admin_host }}"
    login_port: "{{ simple_postgres_admin_port }}"
    login_user: "{{ simple_postgres_admin_user }}"
    login_password: "{{ simple_postgres_admin_password }}"

    db: "{{ simple_postgres_database.name }}"
    name: "{{ db_setting.key }}"
    value: "{{ db_setting.value }}"

  loop: "{{ simple_postgres_database_settings | dict2items }}"
  loop_control:
    loop_var: db_setting
  tags: simple_postgres_database_settings

- name: Provision database application role settings
  funidata.infra.postgresql_role_settings:
    login_host: "{{ simple_postgres_admin_host }}"
    login_port: "{{ simple_postgres_admin_port }}"
    login_user: "{{ simple_postgres_admin_user }}"
    login_password: "{{ simple_postgres_admin_password }}"

    role: "{{ simple_postgres_database.user }}"
    settings:
      # https://github.com/pgaudit/pgaudit/blob/master/README.md#pgauditlog
      pgaudit.log: "{{ simple_postgres_database_user_pgaudit_log }}"
  tags: simple_postgres_database_user_settings

#
# read_role
#

- name: Provision database read role
  postgresql_user:
    login_host: "{{ simple_postgres_admin_host }}"
    login_port: "{{ simple_postgres_admin_port }}"
    login_user: "{{ simple_postgres_admin_user }}"
    login_password: "{{ simple_postgres_admin_password }}"

    name: "{{ simple_postgres_database.read_role | default(simple_postgres_database_read_role) }}"
    role_attr_flags: NOLOGIN
    no_password_changes: true # attempts to ... WITH ENCRYPTED PASSWORD NULL ... on RDS
  tags: simple_postgres_database_read_role

- name: Grant database read role database privileges
  postgresql_privs:
    login_host: "{{ simple_postgres_admin_host }}"
    login_port: "{{ simple_postgres_admin_port }}"
    login_user: "{{ simple_postgres_admin_user }}"
    login_password: "{{ simple_postgres_admin_password }}"

    # GRANT CONNECT, TEMPORARY ON DATABASE ... TO ...
    database: "{{ simple_postgres_database.name }}"
    type: database
    privs: CONNECT,TEMPORARY
    roles: "{{ simple_postgres_database.read_role | default(simple_postgres_database_read_role) }}"
  tags: simple_postgres_database_read_role

- name: Provision database read role schema privileges
  postgresql_privs:
    login_host: "{{ simple_postgres_admin_host }}"
    login_port: "{{ simple_postgres_admin_port }}"
    login_user: "{{ simple_postgres_admin_user }}"
    login_password: "{{ simple_postgres_admin_password }}"

    # GRANT USAGE ON SCHEMA ... TO ...
    database: "{{ simple_postgres_database.name }}"
    type: schema
    objs: public
    privs: USAGE
    roles: "{{ simple_postgres_database.read_role | default(simple_postgres_database_read_role) }}"
  tags: simple_postgres_database_read_role

# Use default privileges to grant access to tables added in the future
- name: Provision database read role default select privileges
  postgresql_privs:
    login_host: "{{ simple_postgres_admin_host }}"
    login_port: "{{ simple_postgres_admin_port }}"
    login_user: "{{ simple_postgres_admin_user }}"
    login_password: "{{ simple_postgres_admin_password }}"
    session_role: "{{ simple_postgres_database.user }}" # requires execution as superuser or altered role

    # ALTER DEFAULT PRIVILEGES FOR USER ... IN SCHEMA ... GRANT SELECT ON TABLES TO ...
    database: "{{ simple_postgres_database.name }}"
    type: default_privs
    target_roles: "{{ simple_postgres_database.user }}"
    schema: public
    privs: SELECT
    objs: TABLES,SEQUENCES
    roles: "{{ simple_postgres_database.read_role | default(simple_postgres_database_read_role) }}"
  tags: simple_postgres_database_read_role

- name: Provision database read role schema table select privileges
  postgresql_privs:
    login_host: "{{ simple_postgres_admin_host }}"
    login_port: "{{ simple_postgres_admin_port }}"
    login_user: "{{ simple_postgres_admin_user }}"
    login_password: "{{ simple_postgres_admin_password }}"

    # GRANT SELECT ON ALL TABLES IN SCHEMA ... TO ...
    database: "{{ simple_postgres_database.name }}"
    schema: public
    type: table
    privs: SELECT
    objs: ALL_IN_SCHEMA
    roles: "{{ simple_postgres_database.read_role | default(simple_postgres_database_read_role) }}"
  tags: simple_postgres_database_read_role

- name: Provision database read role schema sequence select privileges
  postgresql_privs:
    login_host: "{{ simple_postgres_admin_host }}"
    login_port: "{{ simple_postgres_admin_port }}"
    login_user: "{{ simple_postgres_admin_user }}"
    login_password: "{{ simple_postgres_admin_password }}"

    # GRANT SELECT ON ALL SEQUENCES IN SCHEMA ... TO ...
    database: "{{ simple_postgres_database.name }}"
    schema: public
    type: sequence
    privs: SELECT
    objs: ALL_IN_SCHEMA
    roles: "{{ simple_postgres_database.read_role | default(simple_postgres_database_read_role) }}"
  tags: simple_postgres_database_read_role

# Read users
- name: Grant user database read role membership
  funidata.infra.postgresql_role_members:
    login_host: "{{ simple_postgres_admin_host }}"
    login_port: "{{ simple_postgres_admin_port }}"
    login_user: "{{ simple_postgres_admin_user }}"
    login_password: "{{ simple_postgres_admin_password }}"

    role: "{{ simple_postgres_database.read_role | default(simple_postgres_database_read_role) }}"
    members: "{{ simple_postgres_database_read_users }}"
    strict_membership: true
  tags:
    - simple_postgres_database_users
    - simple_postgres_database_read_users

#
# admin_role
#

- name: Provision database admin role
  postgresql_user:
    login_host: "{{ simple_postgres_admin_host }}"
    login_port: "{{ simple_postgres_admin_port }}"
    login_user: "{{ simple_postgres_admin_user }}"
    login_password: "{{ simple_postgres_admin_password }}"

    name: "{{ simple_postgres_database.admin_role | default(simple_postgres_database_admin_role) }}"
    role_attr_flags: NOLOGIN
    no_password_changes: true # attempts to ... WITH ENCRYPTED PASSWORD NULL ... on RDS
  tags: simple_postgres_database_admin_role

- name: Grant database admin role database privileges
  postgresql_privs:
    login_host: "{{ simple_postgres_admin_host }}"
    login_port: "{{ simple_postgres_admin_port }}"
    login_user: "{{ simple_postgres_admin_user }}"
    login_password: "{{ simple_postgres_admin_password }}"

    # GRANT ALL ON DATABASE ... TO ...
    database: "{{ simple_postgres_database.name }}"
    type: database
    privs: ALL
    roles: "{{ simple_postgres_database.admin_role | default(simple_postgres_database_admin_role) }}"
  tags: simple_postgres_database_admin_role

- name: Provision database admin role schema privileges
  postgresql_privs:
    login_host: "{{ simple_postgres_admin_host }}"
    login_port: "{{ simple_postgres_admin_port }}"
    login_user: "{{ simple_postgres_admin_user }}"
    login_password: "{{ simple_postgres_admin_password }}"

    # GRANT ALL ON SCHEMA ... TO ...
    database: "{{ simple_postgres_database.name }}"
    type: schema
    objs: public
    privs: ALL
    roles: "{{ simple_postgres_database.admin_role | default(simple_postgres_database_admin_role) }}"
  tags: simple_postgres_database_admin_role

# Use default privileges to grant access to tables added in the future
- name: Provision database admin role default privileges
  postgresql_privs:
    login_host: "{{ simple_postgres_admin_host }}"
    login_port: "{{ simple_postgres_admin_port }}"
    login_user: "{{ simple_postgres_admin_user }}"
    login_password: "{{ simple_postgres_admin_password }}"
    session_role: "{{ simple_postgres_database.user }}" # requires execution as superuser or altered role

    # ALTER DEFAULT PRIVILEGES FOR USER ... IN SCHEMA ... GRANT SELECT ON TABLES TO ...
    database: "{{ simple_postgres_database.name }}"
    type: default_privs
    target_roles: "{{ simple_postgres_database.user }}"
    schema: public
    privs: ALL
    objs: TABLES,SEQUENCES
    roles: "{{ simple_postgres_database.admin_role | default(simple_postgres_database_admin_role) }}"
  tags: simple_postgres_database_admin_role

- name: Provision database admin role schema privileges
  postgresql_privs:
    login_host: "{{ simple_postgres_admin_host }}"
    login_port: "{{ simple_postgres_admin_port }}"
    login_user: "{{ simple_postgres_admin_user }}"
    login_password: "{{ simple_postgres_admin_password }}"

    # GRANT SELECT ON ALL TABLES IN SCHEMA ... TO ...
    database: "{{ simple_postgres_database.name }}"
    schema: public
    type: table
    privs: ALL
    objs: ALL_IN_SCHEMA
    roles: "{{ simple_postgres_database.admin_role | default(simple_postgres_database_admin_role) }}"
  tags: simple_postgres_database_admin_role

- name: Provision database admin role schema sequence privileges
  postgresql_privs:
    login_host: "{{ simple_postgres_admin_host }}"
    login_port: "{{ simple_postgres_admin_port }}"
    login_user: "{{ simple_postgres_admin_user }}"
    login_password: "{{ simple_postgres_admin_password }}"

    # GRANT SELECT ON ALL SEQUENCES IN SCHEMA ... TO ...
    database: "{{ simple_postgres_database.name }}"
    schema: public
    type: sequence
    privs: ALL
    objs: ALL_IN_SCHEMA
    roles: "{{ simple_postgres_database.admin_role | default(simple_postgres_database_admin_role) }}"
  tags: simple_postgres_database_admin_role

# Admin users
- name: Grant user database admin role membership
  funidata.infra.postgresql_role_members:
    login_host: "{{ simple_postgres_admin_host }}"
    login_port: "{{ simple_postgres_admin_port }}"
    login_user: "{{ simple_postgres_admin_user }}"
    login_password: "{{ simple_postgres_admin_password }}"

    role: "{{ simple_postgres_database.admin_role | default(simple_postgres_database_admin_role) }}"
    members: "{{ simple_postgres_database_admin_users }}"
    strict_membership: true
  tags:
    - simple_postgres_database_users
    - simple_postgres_database_admin_users
