- name: System group
  group:
    gid: "{{ sis_importer_gid }}"
    name: sis-importer
    state: present
    system: true
  tags:
    - sis_importer_mankeli_user

- name: System user
  user:
    uid: "{{ sis_importer_uid }}"
    name: sis-importer
    group: sis-importer
    state: present
    system: true
    create_home: false
  tags:
    - sis_importer_mankeli_user

- name: Config directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: root
    group: sis-importer
  with_items:
    - /opt/sis-importer-mankeli
    - /opt/sis-importer-mankeli/config

- name: Generate env secrets
  copy:
    content: |
      DB_PASSWORD={{ sis_importer_postgres_importer_db_database.password }}
      NATS_TOKEN={{ sis_importer_nats_auth_token }}
    dest: /opt/sis-importer-mankeli/secrets.env
    owner: root
    group: sis-importer
    mode: 0640
  diff: "{{ diff_secrets | default(false) }}"
  tags: sis_importer_mankeli_secret_envs

## backend
- name: Pull backend Docker image
  docker_image:
    name: "{{ sis_importer_mankeli_docker_image }}"
    state: present
    source: pull
    force_source: yes
  tags: sis_importer_mankeli_docker_image

- name: Deploy mankeli Docker container
  docker_container:
    name: sis-importer.mankeli
    image: "{{ sis_importer_mankeli_docker_image }}"
    labels:
      fi.funidata.sis-importer.application: mankeli
      fi.funidata.sis-importer.deploy: "{{ sis_importer_version }}"
      fi.funidata.sis-importer.site: "{{ sis_importer_site }}"
    state: started
    restart_policy: unless-stopped
    network_mode: host
    user: "{{ sis_importer_uid }}:{{ sis_importer_gid }}"
    env:
      DB_USERNAME: "{{ sis_importer_postgres_importer_db_database.user }}"
      DB_PORT: "{{ oodikone_postgres_port | to_json }}"
      DB_HOST: "{{ oodikone_postgres_host }}"
      DB_DATABASE: "{{ sis_importer_postgres_importer_db_database.name }}"
      NATS_URI: "{{ sis_importer_nats_uri }}"
      REDIS_URI: "{{ sis_importer_valkey_uri }}"
      HOSTNAME: "{{ sis_importer_site }}-mankeli" # defines NATS client_id
      SERVICE_PROVIDER: fd
      NODE_ENV: "{{ sis_importer_node_env }}"
    env_file: /opt/sis-importer-mankeli/secrets.env
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - net_raw
    log_driver: "{{ docker_log_driver }}"
    log_options: "{{ docker_log_opts | combine({ 'tag': 'sis-importer.mankeli' }) }}"
  register: sis_importer_mankeli_docker_container
  tags: sis_importer_mankeli_docker_container
