sis_importer_site: sis-importer-dev

sis_importer_sis_host: https://sis-demo.funidata.fi
sis_importer_sis_integration_user: funidata-oodikone-dev.e
sis_importer_root_org_id: testu-university-root-id

sis_importer_version: infra-dev-20240816-01
sis_importer_node_env: production

sis_importer_api_sonic: 1
