oodikone_site: oodikone-jyu-prod # matching name with sis_importer_site
oodikone_server_name: oodikone.jyu.fi

oodikone_sis_application_account: oodikone-jyu-prod
oodikone_sis_host: https://sisu.jyu.fi
oodikone_root_org_id: jyu-university-root-id

oodikone_version: jenkins-aws-oodikone-master-209
oodikone_node_env: production

oodikone_sis_updater_scheduler_max_old_space_size: 1024

oodikone_nginx_identity_providers:
  - "{{ oodikone_nginx_env_configs_identityProvider_JYU }}"

oodikone_nginx_env_configs_identityProvider_JYU:
  name: JYU Login
  navigate: /Shibboleth.sso/JYULogin?target=

# DB needs to have user row ready in order for login to work
oodikone_app_users:
  - full_name: Jukka T. Honkala
    eppn: jutahonk@jyu.fi
    language: fi
    sisu_person_id: jy-jutahonk
    roles:
      - admin
      - courseStatistics
      - studyGuidanceGroups
      - facultyStatistics
      - teachers
    programme_rights: []
  - full_name: Kirsi Rinnesalo
    eppn: kirkopo@jyu.fi
    language: fi
    sisu_person_id: jy-kirkopo
    roles:
      - admin
      - courseStatistics
      - studyGuidanceGroups
      - facultyStatistics
      - teachers
    programme_rights: []
  - full_name: Anna Saastamoinen
    eppn: ankamesa@jyu.fi
    language: fi
    sisu_person_id: jy-ankamesa
    roles:
      - admin
      - courseStatistics
      - studyGuidanceGroups
      - facultyStatistics
      - teachers
    programme_rights: []

oodikone_backend_organisation_config:
  facultyCodes:
    - "urn:organisation:jyu-avoinyo / jy-ORG-12"
    - "urn:organisation:jyu-htk / jy-ORG-24"
    - "urn:organisation:jyu-itk / jy-ORG-25"
    - "urn:organisation:jyu-jsbe / jy-ORG-27"
    - "urn:organisation:jyu-ktk / jy-ORG-39"
    - "urn:organisation:jyu-kyc / jy-ORG-41"
    - "urn:organisation:jyu-ltk / jy-ORG-52"
    - "urn:organisation:jyu-mltk / jy-ORG-55"
    - "urn:organisation:jyu-kie / jy-ORG-35"
  magicFacultyCode: "urn:organisation:jyu-itk / jy-ORG-25"
  ignoredFacultyCodes: []
