oodikone_site: oodikone-jyu-prod # matching name with oodikone_site

sis_importer_sis_host: https://sisu.jyu.fi
sis_importer_sis_integration_user: jyu-oodikone-prod.e
sis_importer_root_org_id: jyu-university-root-id

sis_importer_version: jenkins-aws-sis-importer-master-108
sis_importer_node_env: production

sis_importer_api_sonic: 1
