# placeholder vars, we should probably reserve uid/gid for nats
# nats_gid:
# nats_group_name:
# nats_uid:
# nats_user_name:

nats_cid: nats
nats_client_port: 4222
nats_http_port: 8222
nats_max_msgs: 5000
