- name: System group
  group:
    gid: "{{ sis_importer_gid }}"
    name: sis-importer
    state: present
    system: true
  tags:
    - sis_importer_db_api_user

- name: System user
  user:
    uid: "{{ sis_importer_uid }}"
    name: sis-importer
    group: sis-importer
    state: present
    system: true
    create_home: false
  tags:
    - sis_importer_db_api_user

- name: Config directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: root
    group: sis-importer
  with_items:
    - /opt/sis-importer-db-api
    - /opt/sis-importer-db-api/config

- name: Generate env secrets
  copy:
    content: |
      DB_PASSWORD={{ sis_importer_postgres_importer_db_database.password }}
    dest: /opt/sis-importer-db-api/secrets.env
    owner: root
    group: sis-importer
    mode: 0640
  diff: "{{ diff_secrets | default(false) }}"
  tags: sis_importer_db_api_secret_envs

## backend
- name: Pull backend Docker image
  docker_image:
    name: "{{ sis_importer_db_api_docker_image }}"
    state: present
    source: pull
    force_source: yes
  tags: sis_importer_db_api_docker_image

- name: Deploy db-api Docker container
  docker_container:
    name: sis-importer.db-api
    image: "{{ sis_importer_db_api_docker_image }}"
    labels:
      fi.funidata.sis-importer.application: db-api
      fi.funidata.sis-importer.deploy: "{{ sis_importer_version }}"
      fi.funidata.sis-importer.site: "{{ sis_importer_site }}"
    state: started
    restart_policy: unless-stopped
    network_mode: host
    user: "{{ sis_importer_uid }}:{{ sis_importer_gid }}"
    env:
      DB_USERNAME: "{{ sis_importer_postgres_importer_db_database.user }}"
      DB_PORT: "{{ sis_importer_postgres_port | to_json }}"
      DB_HOST: "{{ sis_importer_postgres_host }}"
      DB_DATABASE: "{{ sis_importer_postgres_importer_db_database.name }}"
      REDIS_URI: "{{ sis_importer_valkey_uri }}"
      SIS_API_URL: "{{ sis_importer_sis_host }}"
      SERVICE_PROVIDER: fd
    env_file: /opt/sis-importer-db-api/secrets.env
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - net_raw
    log_driver: "{{ docker_log_driver }}"
    log_options: "{{ docker_log_opts | combine({ 'tag': 'sis-importer.db-api' }) }}"
  register: sis_importer_db_api_docker_container
  tags: sis_importer_db_api_docker_container

- name: Wait for sis-importer.db-api startup
  uri:
    url: "http://127.0.0.1:3000/health"
    method: GET
    status_code: [200,403] # backend expects authenticated requests
  register: result
  when: not ansible_check_mode
  until: result.status in [200,403]
  retries: 60
  delay: 1
  tags: sis_importer_db_api_wait
