- hosts: aws_oodikone_app:aws_sis_importer_app
  run_once: true # generate one password
  tasks:
    - name: Generate user passsword
      set_fact:
        oodikone_postgres_user_password: "{{ lookup('password', '/dev/null chars=ascii_lowercase,ascii_uppercase,digits length=%d' | format(oodikone_postgres_user_password_length)) }}"

    - name: Output user password
      debug:
        msg: "New password for {{ oodikone_postgres_user }}: {{ oodikone_postgres_user_password }}"

- hosts: aws_oodikone_app
  run_once: true # assume single PostgreSQL server for apps in environment
  tasks:
    - name: Reset PostgreSQL user password
      postgresql_user:
        login_host: "{{ oodikone_postgres_admin_host }}"
        login_port: "{{ oodikone_postgres_admin_port }}"
        login_user: "{{ oodikone_postgres_admin_user }}"
        login_password: "{{ oodikone_postgres_admin_password }}"

        db: "{{ oodikone_postgres_database }}"
        name: "{{ oodikone_postgres_user }}"
        role_attr_flags: LOGIN
        password: "{{ oodikone_postgres_user_password }}"
      loop: 
        - "{{ oodikone_postgres_kone_db_database.name }}"
        - "{{ oodikone_postgres_sis_db_database.name }}"
        - "{{ oodikone_postgres_user_db_database.name }}"
      loop_control:
        loop_var: oodikone_postgres_database

- hosts: aws_sis_importer_app
  run_once: true
  tasks:
    - name: Reset PostgreSQL user password
      postgresql_user:
        login_host: "{{ oodikone_postgres_admin_host }}"
        login_port: "{{ oodikone_postgres_admin_port }}"
        login_user: "{{ oodikone_postgres_admin_user }}"
        login_password: "{{ oodikone_postgres_admin_password }}"

        db: "{{ sis_importer_postgres_importer_db_database.name }}"
        name: "{{ oodikone_postgres_user }}"
        role_attr_flags: LOGIN
        password: "{{ oodikone_postgres_user_password }}"
