oodikone_site: oodikone-tuni-demo # matching name with sis_importer_site
oodikone_server_name: oodikone-tuni-demo.funidata.fi

oodikone_sis_application_account: oodikone-tuni-demo
oodikone_sis_host: https://sis-tuni-staging.funidata.fi
oodikone_root_org_id: tuni-university-root-id

oodikone_version: jenkins-aws-oodikone-master-302
oodikone_node_env: production

oodikone_sis_updater_worker_max_old_space_size: 1536
oodikone_backend_max_old_space_size: 1536

oodikone_nginx_identity_providers:
  - "{{ oodikone_nginx_env_configs_identityProvider_TUNI }}"

oodikone_nginx_env_configs_identityProvider_TUNI:
  name: TUNI Login
  navigate: /Shibboleth.sso/TUNILogin?target=

# DB needs to have user row ready in order for login to work
oodikone_app_users:
  - full_name: Piia Asunmaa
    eppn: lahtin45@tuni.fi
    language: fi
    sisu_person_id: tuni-person-lahtin45
    roles:
      - admin
      - courseStatistics
      - studyGuidanceGroups
      - facultyStatistics
      - teachers
    programme_rights: []
  - full_name: Suvi-Päivikki Ikonen
    eppn: viitala4@tuni.fi
    language: fi
    sisu_person_id: tuni-person-viitala4
    roles:
      - admin
      - courseStatistics
      - studyGuidanceGroups
      - facultyStatistics
      - teachers
    programme_rights: []
  - full_name: Ville-Matti Erkintalo
    eppn: ve73680@tuni.fi
    language: fi
    sisu_person_id: tuni-person-ve73680
    roles:
      - admin
      - courseStatistics
      - studyGuidanceGroups
      - facultyStatistics
      - teachers
    programme_rights: []
  - full_name: Sari Pulkkinen
    eppn: stsasa@tuni.fi
    language: fi
    sisu_person_id: tuni-person-stsasa
    roles:
      - admin
      - courseStatistics
      - studyGuidanceGroups
      - facultyStatistics
      - teachers
    programme_rights: []
  - full_name: Marja-Liisa Laine
    eppn: laine38@tuni.fi
    language: fi
    sisu_person_id: tuni-person-laine38
    roles:
      - admin
      - courseStatistics
      - studyGuidanceGroups
      - facultyStatistics
      - teachers
    programme_rights: []
  - full_name: Jaana Kunnari
    eppn: jinha@tuni.fi
    language: fi
    sisu_person_id: tuni-person-jinha
    roles:
      - admin
      - courseStatistics
      - studyGuidanceGroups
      - facultyStatistics
      - teachers
    programme_rights: []
  - full_name: Soila Uskola
    eppn: kolari3@tuni.fi
    language: fi
    sisu_person_id: tuni-person-kolari3
    roles:
      - admin
      - courseStatistics
      - studyGuidanceGroups
      - facultyStatistics
      - teachers
    programme_rights: []
  - full_name: Arja Tusa
    eppn: tusaa@tuni.fi
    language: fi
    sisu_person_id: tuni-person-tusaa
    roles:
      - admin
      - courseStatistics
      - studyGuidanceGroups
      - facultyStatistics
      - teachers
    programme_rights: []

oodikone_backend_organisation_config:
  facultyCodes:
    - tuni-1301000002
    - tuni-1301000060
    - tuni-1301000008
    - tuni-1301000015
    - tuni-1301000059
    - tuni-1301000057
    - tuni-1301000058
    - tuni-1301000018
    - tuni-1301000022
    - tuni-1301000026
    - tuni-1301000549
    - tuni-1301000031
    - tuni-1301000077
  magicFacultyCode: tuni-1301000002
  ignoredFacultyCodes: []
