oodikone_registry_base: 637423527834.dkr.ecr.eu-north-1.amazonaws.com/oodikone

oodikone_backend_docker_image: "{{ oodikone_registry_base }}/oodikone-backend:{{ oodikone_version }}"
oodikone_frontend_docker_image: "{{ oodikone_registry_base }}/oodikone-frontend:{{ oodikone_version }}"

oodikone_sis_updater_nats_docker_image: "nats-streaming:0.25.6"

oodikone_sis_updater_scheduler_docker_image: "{{ oodikone_registry_base }}/updater-scheduler:{{ oodikone_version }}"
oodikone_sis_updater_worker_docker_image: "{{ oodikone_registry_base }}/updater-worker:{{ oodikone_version }}"

oodikone_valkey_host: localhost
oodikone_valkey_uri: "//{{ oodikone_valkey_host }}:{{ valkey_port }}"

oodikone_sis_updater_scheduler_url: http://localhost:8082
oodikone_sis_importer_db_api_url: "http://{{ importer_db_api_host }}:3000"
