ansible_ca_bundle: /etc/ssl/certs/ca-bundle.crt # on host

# compat with:
# * CentOS 7 / python3 (3.6)
# * CentOS 8 / python36 (3.6)
# * Amazon Linux 2 / python3 (3.7)
ansible_python_interpreter: /usr/bin/python3

# INFRA-791: bump ControlPersist to avoid SIGPIPE race conditions with task executions coinciding with ssh ControlMaster timeouts
# use StrictHostKeyChecking=accept-new to reject changed host keys (OpenSSH 7.6+)
# use versioned per-host ssh known_hosts files
ansible_ssh_args: "-o ControlMaster=auto -o ControlPersist=300s -o StrictHostKeyChecking=accept-new -o UserKnownHostsFile={{ playbook_dir }}/ssh/known_hosts.d/{{ inventory_hostname }} -o HashKnownHosts=no -o ServerAliveInterval=5 -o ServerAliveCountMax=1"

# optional SSH jumphost, not used by default (assumes AWS ops VPN)
ansible_ssh_jumphost: "{{ lookup('env', 'ANSIBLE_SSH_JUMPHOST')}}"
ansible_ssh_jumphost_user: "{{ lookup('env', 'ANSIBLE_SSH_JUMPHOST_USER')}}"
ansible_ssh_common_args: "{% if ansible_ssh_jumphost %}-o ProxyJump={% if ansible_ssh_jumphost_user %}{{ ansible_ssh_jumphost_user }}@{% endif %}{{ ansible_ssh_jumphost }}{% endif %}"
