oodikone_postgres_username: oodikone
oodikone_postgres_password: "{{ postgres_passwords[oodikone_postgres_username] }}"
oodikone_postgres_databases:
  - kone-db
  - sis-db
  - user-db

oodikone_postgres_host: oodikone-postgres-dev
oodikone_postgres_port: 5432
oodikone_postgres_user_password_length: 32

oodikone_postgres_db_dumps:
  kone-db: files/oodikone-postgres/kone-db.sqz
  sis-db: files/oodikone-postgres/sis-db.sqz
  user-db: files/oodikone-postgres/user-db.sqz